services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql # SQL script for seeding db with data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment:
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/server.json
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
      - ./data/pgadmin_server_config.json:/var/lib/pgadmin/server.json

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: